### PR TITLE
upgrade the dev dependency clap from 2.33 to 3

### PR DESCRIPTION
**Pull request by alexanderkjall**
I know clap 4 is out, but clap 3 is the version that is currently packaged in Debian sid, and it's still an improvement to go from 2 -> 3 I think.

### CODE REVIEW

**Comment by cardoe** [comment]
This would involve a semver change as it affects the MSRV. Since it's just a change in the examples it doesn't seem high priority to me. We can rebase this once we've gotten other updates that require bumping the MSRV or if the `log` crate increases their MSRV then we'll match that.

**Comment by cardoe** [comment]
Snipping your code style updates as a different commit.

**Comment by alexanderkjall** [comment]
I didn't fully understand that comment about code style? But feel free to use this however you want :)

**Comment by cardoe** [comment]
Ah I'm wrong. We needed to use a MSRV lock file due to once_cell's change. But we can merge this in.

**Pull request merged**
