### PR TITLE
Do not emit control chars if stderr is not a tty

### LINKED ISSUE #14: Don't colorize if stderr is not a tty
Currently even if using `ColorChoice::Auto`, stderrlog will use colors when piping to files, ex. `cargo run 2>&1 > log.txt`. This causes the log to have control characters in it, which is annoying and doesn't mirror what other unix tools do.

When using `ColorChoice::Auto`, stderrlog should check if stderr is a TTY (ex. by using the `isatty` crate) and disable colors if it isn't.

### PR DESCRIPTION
**Pull request by thiagoarrais**
Fixes #14

I think this works, but I couldn't figure out how to write proper tests. Would love some direction on that regard.

### CODE REVIEW

**Comment by thiagoarrais** [comment]
CI failure seems to be related to an incompatibility of `cfg-if` with rust 1.16. Should `Cargo.lock` be commited to avoid that?

**Comment by ypoluektovich** [comment]
> Should Cargo.lock be commited to avoid that?
Not into the repository root.
But there may be a way to prepare a Cargo.lock that would be inserted in that specific CI job...

**Comment by cardoe** [comment]
We just need to bump the minimum Rust version.

**Comment by cardoe** [comment]
https://github.com/rust-lang-nursery/log/issues/358 is why the tests fail.

**Comment by cardoe** [comment]
Ultimately I'd rather see us set this once when initializing rather than a call on every `log()` invocation.

**Comment by cardoe** [comment]
https://github.com/cardoe/stderrlog-rs/tree/thiagoarrais-isatty has a commit on top to do the tty check at setup time. This will save a syscall on every `log()`.

**Comment by thiagoarrais** [comment]
@cardoe: changes incorporated. Thanks for the feedback. I've been meaning to place the check in the setup, but wasn't really sure the tty was guaranteed to remain the same for the hole duration of the program.

**Comment by thiagoarrais** [comment]
Anything else needed here?

**Comment by cardoe** [comment]
@ypoluektovich You're totally right. Not sure what I was thinking.

@thiagoarrais time basically.

**Comment by cardoe** [comment]
@ypoluektovich & @thiagoarrais https://github.com/cardoe/stderrlog-rs/tree/thiagoarrais-isatty

**Comment by cardoe** [comment]
Thanks for the PR and for working with my delay in responding. We can do a follow on if this isn't what you wanted but I merged it so that there's no more delay in getting it out.

**Comment by cardoe** [comment]
I released 0.4.2 with this change in it.

**Comment by thiagoarrais** [comment]
No problem! Thanks for removing the old code that I left in, by the way...

**Pull request closed without merging**
