### PR TITLE
switch to time from chrono

### LINKED ISSUE #31: Chrono dependency involves insecure version
```
   = ID: RUSTSEC-2020-0071
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0071
   = ### Impact
     
     Unix-like operating systems may segfault due to dereferencing a dangling pointer in specific circumstances. This requires an environment variable to be set in a different thread than the affected functions. This may occur without the user's knowledge, notably in a third-party library.
     
     The affected functions from time 0.2.7 through 0.2.22 are:
     
     - `time::UtcOffset::local_offset_at`
     - `time::UtcOffset::try_local_offset_at`
     - `time::UtcOffset::current_local_offset`
     - `time::UtcOffset::try_current_local_offset`
     - `time::OffsetDateTime::now_local`
     - `time::OffsetDateTime::try_now_local`
     
     The affected functions in time 0.1 (all versions) are:
     
     - `at`
     - `at_utc`
     - `now`
     
     Non-Unix targets (including Windows and wasm) are unaffected.
     
     ### Patches
     
     Pending a proper fix, the internal method that determines the local offset has been modifan `Err` on the `try_*` methods and `UTC` on the non-`try_*` methods.
     
     Users and library authors with time in their dependency tree should perform `cargo update     
     Users of time 0.1 do not have a patch and should upgrade to an unaffected version: time 0     
     ### Workarounds
     
     No workarounds are known.
     
     ### References
     
     time-rs/time#293
   = Announcement: https://github.com/time-rs/time/issues/293
   = Solution: Upgrade to >=0.2.23
   = time v0.1.43
     └── chrono v0.4.19
         └── stderrlog v0.5.1
             └── fil4prod v0.1.0
```

I have personally solved this by switching dependency from `chrono` to `time` directly, since the latter basically sufficed and `chrono` does not appear to be getting updated in near term (https://github.com/chronotope/chrono/pull/578).

### PR DESCRIPTION
**Pull request by cardoe**
chrono is no longer maintained and has a long standing security issue in
it. Switched to time to resolve the security issue. fixes #31.

### CODE REVIEW

**Comment by cardoe** [comment]
Unfortunately the time crate appears to only support second resolution in their formatting and nothing sub-second per https://github.com/time-rs/time/blob/d26562b930aa59ab4934ef6eb790474ff506126b/src/format/parse_items.rs#L55

**Comment by virtualritz** [comment]
> chrono is no longer maintained [...]

`chrono` seems [actively maintained](https://github.com/chronotope/chrono/commit/82407ffa9e3f594f577868062ac76622eb1cfd52) to me.
Since I rely on this crate a lot in production critical code and would need to switch if what you write was true: can you substantiate this claim?

**Comment by cardoe** [comment]
Certainly at the time of my comment it was valid. It had 0 commits and 0 comments on issues by maintainers for 4 months and the preceding year it only had about a dozen commits. There were a few opened issues asking if it was maintained with no comments and folks in the Rust community were recommending switching back to time 0.3.

Given it getting maintenance again I’ll retire this PR and move forward with an updated release.

**Comment by cardoe** [comment]
You can see issues like https://github.com/rustsec/advisory-db/issues/1216 which have been calling into question it’s maintained status.

**Comment by cardoe** [comment]
https://github.com/chronotope/chrono/issues/650#issuecomment-1075871826 It appears to be more revived around Feb 27th.

**Comment by cardoe** [comment]
We've yet to see a chrono release since work restarted on the project.

**Pull request closed without merging**
